### ISSUE TITLE
Add More Cpp Algorithms and Also try Some other Languages.

### ISSUE THREAD

**Issue by Kushal-W** [Kushal-W/hacktoberfest-cppalgo#5]
Try to add different algorithms in languages like-
1.Python
2.Java
3.Javascript

Create different folders for all the algorithms.

The code should be complete and clear.

**Comment by Aditya-wani02** [comment]
Assign me.

**Comment by yashsarnaik22** [comment]
Please assign me, I will add some CPP codes.

**Comment by Sakshi2002-Sinha** [comment]
hello, Can you assign me this issue. I can do it all in C++.
